# coding=utf-8


BAREWORDS = {
    "compressionmode"       : "CompressionMode",
    "decompress"            : "Decompress",
    "memorystream"          : "MemoryStream",
    "text"                  : "Text",
    "encoding"              : "Encoding",
    "ascii"                 : "ASCII",
    "length"                : "Length",
    "readtoend"             : "ReadToEnd",
    "compression"           : "Compression",
    "deflatestream"         : "DeflateStream",
    "streamreader"          : "StreamReader",
    "value"                 : "Value",
    "powershell"            : "Powershell",
    "invokecommand"         : "InvokeCommand",
    "invokescript"          : "InvokeScript",
    "securityprotocol"      : "SecurityProtocol",
    "createdirectory"       : "CreateDirectory",
    "webclient"             : "WebClient",
    "new"                   : "New",
    "set"                   : "Set",
    "type"                  : "Type",
    "environment"           : "Environment",
    "variable"              : "Variable",
    "downloadfile"          : "DownloadFile",
    "create"                : "Create",
    "frombase64string"      : "FromBase64String",
    "tobase64string"        : "ToBase64String",
    "getenvironmentvariable": "GetEnvironmentVariable",
    "replace"               : "Replace",
    "split"                 : "Split",
    "system"                : "System",
    "io"                    : "IO",
    "directory"             : "Directory",
    "net"                   : "Net",
    "servicepointmanager"   : "ServicePointManager",
    "convert"               : "Convert",
    "invoke"                : "Invoke",
    "foreach"               : "ForEach",
    "object"                : "Object",
    "get"                   : "Get",
    "item"                  : "Item",
    "tochararray"           : "ToCharArray",
    "string"                : "String"
}
