# coding=utf-8
OPS = {
    "Minus": " - ",
    "Plus": " + ",
    "Multiply": " * ",
    "Format": " -f ",
    "Equals": " = ",
    "PlusEquals": " += ",
    "PostfixPlusPlus": "++",
    "PostfixMinusMinus": "--",
    "Is": " -is ",
    "As": " -as ",
    "Ieq": " -eq ",
    "Ige": " -ge ",
    "Igt": " -gt ",
    "Ile": " -le ",
    "Ilt": " -lt ",
    "Ine": " -ne ",
    "Bxor": " -bxor ",
    "Ireplace": " -replace ",
    "Join": " -join ",
    "Imatch": " -match ",
    "And": " -and ",
    "Or": " -or ",
    "DotDot": "..",
}
